Update links Tutorial, Libs, etc. Other update in the future! ;-)
0xFA11/MultiplayerNetworkingResources pull request #6
Opened 2018-12-22 20:35 UTC by Vytek

2018-12-22 22:21 UTC, 0xFA11 commented
Thanks for your suggestions!

However, I've spotted a few problems.
**Please read [Contribution Guidelines](https://github.com/MFatihMAR/Awesome-Game-Networking/blob/master/CONTRIBUTING.md) carefully before opening a PR.**

I'll review them one by one and expecting to have individual PRs for them.

Please consider:

> - One add/update per pull request.
> - Entry name in title-case and list in alphabetical order.
> - Entry does not wrap to next-line.

Cheers,
Fatih

2018-12-22 22:27 UTC, 0xFA11 requested changes

2018-12-22 22:27 UTC, 0xFA11 commented on README.md
> +- [ Bernier, Yahn W. (2001)](http://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf) - Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization.
The linked Valve wiki page [Source Multiplayer Networking](https://developer.valvesoftware.com/wiki/Source_Multiplayer_Networking) already includes this paper inline, so this is a duplicate ([see page here](https://developer.valvesoftware.com/wiki/Latency_Compensating_Methods_in_Client/Server_In-game_Protocol_Design_and_Optimization)).

2018-12-22 22:27 UTC, 0xFA11 commented on README.md
> +- [Unity / Multiplayer Networking](https://unity3d.com/learn/tutorials/s/multiplayer-networking) - Official UNET-based multiplayer game networking tutorials by Unity.[
Oh, that's a small accident :(

2018-12-22 22:27 UTC, 0xFA11 commented on README.md
> +- [Unity /Gambetta Networked Demo](https://github.com/RamiAhmed/Gambetta_NetworkedDemo) - Unity Demo showcasing networking concepts including prediction, interpolation and reconciliation in a network
I tend to have this one only, not the local one above.
But, this entry is not in order in the list (_list in alphabetical order_).
Also there is small typo, you should have another space here: "Unity / Gambetta " instead of "Unity /Gambetta"

2018-12-22 22:27 UTC, 0xFA11 commented on README.md
> +- [C# / Barebones-masterserver](https://github.com/alvyxaz/barebones-masterserver) - Master Server framework for Unity.
Not in order in the list (list in alphabetical order).

2018-12-25 06:27 UTC, 0xFA11 commented
Since you never respond to my change request, I manually added relevant links to the list with proper formatting.
Thank you for your suggestions!

2018-12-25 06:27 UTC, closed without merging

2018-12-26 08:36 UTC, Vytek commented
Sorry, I am reading now your suggest. I will follow your Contribuition Guideline. Merru Christams!