Add some more resources
0xFA11/MultiplayerNetworkingResources pull request #64
Opened 2024-01-15 17:01 UTC by gafferongames

2024-01-16 14:32 UTC, gafferongames commented
OK I've finished my pass adding all the resources I can think of. Hope this helps. Thanks!

2024-01-16 23:13 UTC, ThusSpokeNomad requested changes

2024-01-16 23:13 UTC, 0xFA11 commented on README.md
> +  - [Between 2 Servers](https://www.youtube.com/watch?v=-EvO2DOuGos) - Glenn Fiedler interviews gamedevs about multiplayer and netcode.
```suggestion
  - [Between Two Servers](https://www.youtube.com/playlist?list=PLzVi6Kh_HMIWKS1aXOV4XobuymoF0P-_S) - Glenn Fiedler interviews gamedevs about multiplayer and netcode.
```

I just wanted to suggest changing this link to the playlist instead of the first episode — so that people could see the whole playlist overview.

2024-01-17 00:16 UTC, gafferongames commented on README.md
> +  - [Between 2 Servers](https://www.youtube.com/watch?v=-EvO2DOuGos) - Glenn Fiedler interviews gamedevs about multiplayer and netcode.
Good change!

2024-01-17 00:30 UTC, ThusSpokeNomad approved these changes
Fantastic stuff!
I also want to use this chance to personally thank you for all the contributions you did online over the years (articles, videos, projects etc.) — I'm a big fan! :)

2024-01-17 00:35 UTC, merged